### PR TITLE
Csv delim

### PR DESCRIPTION
**Pull request by pedralmeida**
Allow the choice of a delimiter character when exported CSVs do not use comma as separator.

### CODE REVIEW

**Comment by aniav** [comment]
Thank you for the PR @pedralmeida. I will check this within the next week as I am currently traveling 🙌

**Comment by aniav** [comment]
So I think I need a bit more context here. `Papa.parse` has the possibility of automatic delimiter detection and uses each of the list of `[',', '\t', '|', ';', Papa.RECORD_SEP, Papa.UNIT_SEP]`, which covers more cases than your implementation.

From their docs: https://www.papaparse.com/docs#config

Is this not enough for your use case?

**Comment by pedralmeida** [comment]
Hi!

Thank you for looking into it.
Yes, Papa.parse has an automatic way to detect it. However for non-american
countries that use the seicolon as separator, the comma is then used
as *decimal
*delimiter and papaparse interpreted *that *as the delimiter. So I required
a new method to force the separator so it is not fooled.

eg: field;field;3,5;field;field

in this example, papaparse separates the 3,5 creating  *field;field;3 *and
* 5;field;field*  instead of doing via the semicolon.

I believe you can test this by simply manipulating a typical csv and change
all commas by semicolons and vice-versa.


Ania Warzecha <notifications@github.com> escreveu no dia segunda,
17/02/2020 à(s) 15:35:

**Comment by aniav** [comment]
I needed a bit of time to actually get to testing it. I made one improvement to force the "auto" delimiter for people who don't have the delimiter stored in their profile settings in local storage 🙌 Thank you for this change!

**Review by aniav — COMMENTED** [review]
I needed a bit of time to actually get to testing it. I made one improvement to force the "auto" delimiter for people who don't have the delimiter stored in their profile settings in local storage 🙌 Thank you for this change!

**Pull request merged**
